[versions]
gtceu_version = "7.5.0"
ldlib_version = "1.0.47"
registrate_version = "MC1.20-1.3.11"
kubejs_version = "2001.6.4-build.120+forge"
configuration_version = "3.1.0-forge"
jei_version = "15.20.0.121"
emi_version = "1.1.22+1.20.1"
mixinextras_version = "0.5.0-rc.3"
jade_version = "11.13.2+forge"
architectury_version = "9.1.12"
ae2_version = "15.4.10"
guideme_version = "20.1.11"
rhino_version = "2001.2.3-build.6+forge"
embeddium_version = "0.3.30+mc1.20.1"
jech_version = "lNBZNQmX"  # 4.5.16
ftblibrary_version = "5567591"
ftbteams_version = "5267190"
ftbultimine_version = "5363345"
ftbchunks_version = "5378090"
bettergtae_version = "1.2.1"
gtmoremachine_version = "mc1.20.1-1.5.1"

[libraries]
jei-common-api = { module = "mezz.jei:jei-1.20.1-common-api", version.ref = "jei_version" }
jei-forge-api = { module = "mezz.jei:jei-1.20.1-forge-api", version.ref = "jei_version" }
jei-forge-impl = { module = "mezz.jei:jei-1.20.1-forge", version.ref = "jei_version" }
emi = { module = "dev.emi:emi-forge", version.ref = "emi_version" }

gtceu = { module = "com.gregtechceu.gtceu:gtceu-1.20.1", version.ref = "gtceu_version" }
ldlib = { module = "com.lowdragmc.ldlib:ldlib-forge-1.20.1", version.ref = "ldlib_version" }
registrate = { module = "com.tterrag.registrate:Registrate", version.ref = "registrate_version" }
configuration = { module = "dev.toma.configuration:configuration-1.20.1", version.ref = "configuration_version" }
bettergtae = { module = "maven.modrinth:better-gregtech-and-applied-energistics", version.ref = "bettergtae_version" }
gtmoremachine = { module = "maven.modrinth:gtmoremachine", version.ref = "gtmoremachine_version" }

kubejs = { module = "maven.modrinth:kubejs", version.ref = "kubejs_version" }
rhino = { module = "maven.modrinth:rhino", version.ref = "rhino_version" }
architectury = { module = "dev.architectury:architectury-forge", version.ref = "architectury_version" }

jade = { module = "maven.modrinth:jade", version.ref = "jade_version" }

mixinExtras-common = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixinextras_version" }
mixinExtras-forge = { module = "io.github.llamalad7:mixinextras-forge", version.ref = "mixinextras_version" }

ae2 = { module = "appeng:appliedenergistics2-forge", version.ref = "ae2_version" }
guideme = { module = "maven.modrinth:guideme", version.ref = "guideme_version" }

embeddium = { module = "maven.modrinth:embeddium", version.ref = "embeddium_version" }

jech = { module = "maven.modrinth:justenoughcharacters", version.ref = "jech_version" }

ftblibrary = { module = "curse.maven:ftb-library-forge-404465", version.ref = "ftblibrary_version" }
ftbteams = { module = "curse.maven:ftb-teams-forge-404468", version.ref = "ftbteams_version" }
ftbultimine = { module = "curse.maven:ftb-ultimine-forge-386134", version.ref = "ftbultimine_version" }
ftbchunks = { module = "curse.maven:ftb-chunks-forge-314906", version.ref = "ftbchunks_version" }

[bundles]
jei = ["jei-common-api", "jei-forge-api", "jei-forge-impl"]
kjs = ["kubejs", "rhino", "architectury"]